# Generated by Django 5.2.7 on 2025-10-24 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_n_service', '0006_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 25, 2, 35, 58, 219592)),
        ),
    ]
