# Generated by Django 5.2.7 on 2025-10-24 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_n_notification', '0006_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 25, 2, 57, 31, 758437)),
        ),
    ]
